on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Spectra
    steps:
      - uses: actions/checkout@v3
      - name: Spectra action step
        id: scan
        uses: yunsoul/action-test-docker-provider@v1.0
        with:
          target: '*.sol'
          mode: 'A'
      # Use the output from the `scan` step
      - name: Get the output
        run: echo "The time was ${{ steps.scan.outputs.scan-result }}"

